# Generated by Django 4.1.2 on 2022-10-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_upload_category_upload_total_upload_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('monthly_expenses', models.FloatField()),
                ('monthly_budget', models.FloatField()),
                ('annual_salary', models.FloatField()),
                ('state', models.CharField(max_length=2)),
                ('tax_bracket', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='ocr_json',
            field=models.TextField(default=''),
        ),
    ]
