# Generated by Django 4.1.2 on 2022-10-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_personal_finance_alter_upload_ocr_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('monthly_expenses', models.FloatField(null=True)),
                ('monthly_budget', models.FloatField(null=True)),
                ('annual_salary', models.FloatField(null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('tax_bracket', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Personal_Finance',
        ),
    ]
