# Generated by Django 4.1.2 on 2022-10-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_personalfinance_delete_personal_finance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalFinance',
        ),
    ]
