# Generated by Django 4.1.2 on 2022-11-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_personalfinance_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalfinance',
            old_name='input_time',
            new_name='update_time',
        ),
    ]
