# Generated by Django 4.1.2 on 2023-02-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_expenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
